config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users
  resources :courses
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'courseshow' => 'courses#show'
  get 'coursewatch' => 'courses#watch'
  get 'dacourseshow' => 'da_courses#show'
  get 'xiaocourseshow' => 'xiao_courses#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses
  has_many :users, :through => :user_courses
  belongs_to :xiao_course
  belongs_to :da_course


end

app/models/da_course.rb
class DaCourse < ApplicationRecord
  has_many :user_courses
  has_many :users, :through => :user_courses
  has_many :xiao_courses
  has_many :courses

  def name
    content
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_courses
  has_many :courses, :through => :user_courses
  has_many :da_courses, :through => :user_courses
  has_many :xiao_courses, :through => :user_courses

  after_initialize :init

  def init
    self.buytime  ||= 20.0
    self.playtime  ||= 0.0
    self.expiredate ||= Date.today + 365.days
  end

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
  # has_secure_password
  validates :password_digest, length: { minimum: 6 }
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
  belongs_to :da_course
  belongs_to :xiao_course

end

app/models/xiao_course.rb
class XiaoCourse < ApplicationRecord
  has_many :user_courses
  has_many :users, :through => :user_courses
  has_many :courses
  belongs_to :da_course

  def name
    content
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper



end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @user = User.find_by(id: session[:user_id])
    @course = Course.all
    @current_xiaocourse = @user.xiao_courses.find_by(id: params[:xiaocourseid])

  end

  def watch
    @user = User.find_by(id: session[:user_id])
    @current_course = Course.find_by(id: params[:course_now])

    session[:course_time] = Time.now
    @user.save


    #   scheduler = Rufus::Scheduler.new
    #   job = scheduler.schedule_every '1m' do
    #     if  request.original_url.length >= 45 && @user.playtime < @user.buytime*3600
    #       @user.playtime += 60
    #       @user.save
    #     else
    #       job.kill
    #     end
    #   end
  end

end

app/controllers/da_courses_controller.rb
class DaCoursesController < ApplicationController
  def show
    @user = User.find_by(id: session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.password_digest == params[:session][:password]
      if @user.expiredate > Date.today
        log_in @user
        redirect_to dacourseshow_url
      else
        flash.now[:danger] = '帐号已过期!'
        render 'new'
      end

    else
      flash.now[:danger] = '帐号或密码错误!'
      render 'new'
    end

  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user

  def home
  end

  def about
  end

  def login

  end

  def logged_in_user

    unless logged_in?
      flash[:danger] = "请登录."
      redirect_to login_url
    else
      redirect_to dacourseshow_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :timeleft, only: [:show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: '注册成功!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "更新成功!"
        redirect_to @user
      else
        render 'edit'
      end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "请登录."
        redirect_to login_url
      end
    end

    def timeleft
      @user = User.find(params[:id])
      if @user.playtime >= @user.buytime*3600
        redirect_to edit_user_url
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :playtime)
    end
end

app/controllers/xiao_courses_controller.rb
class XiaoCoursesController < ApplicationController
  def show
    @user = User.find_by(id: session[:user_id])
    @current_dacourse = @user.da_courses.find_by(id: params[:dacourseid])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "唯新学院"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/da_courses_helper.rb
module DaCoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id

    # 每周日更新系统
    if session[:user_id] == 1
      scheduler = Rufus::Scheduler.new
      job = scheduler.schedule_every '7d' do
        User.update_all(playtime: 0)
        User.update_all(buytime: 20)
      end
    end


  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def is_admin?
    if logged_in?
      current_user.admin == true
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/xiao_courses_helper.rb
module XiaoCoursesHelper
end

app/views/courses/show.html.erb
<div class="ui link cards">
  <% @course.each do |course| %>
      <%	if course.xiao_course.id == @current_xiaocourse.id%>
          <div class="card">
            <a class="image" href="/coursewatch?course_now=<%= course.id %>">
              <img src=<%= course.imageurl %>>
            </a>
            <div class="content">
              <div class="header"><%= course.content %></div>
              <div class="meta">

              </div>
              <div class="description">

              </div>
            </div>
            <div class="extra content">

            </div>
          </div>
      <% end %>

  <% end %>
</div>

app/views/courses/watch.html.erb
<div style="position: relative;padding-bottom: 56.25%;" >
  <video id="player" style="position: absolute;top: 0;left: 0;width: 100%;height: 100%;" controls>
    <source src=<%=	@current_course.videourl %> type="video/mp4">
  </video>

</div>


<script>


  var isActive = true;

  window.onfocus = function () {
    isActive = true;
  };

  window.onblur = function () {
    isActive = false;
  };

  var count = 0;
  var countup = function(){

    if(!window.isActive ){
      count++;
    }else {
      count = 0;
    }

  };
  var id = setInterval(function(){
    countup();
    if(count > 0){
      clearInterval(id);
      document.location.href="/";
    }}, 300000);
//  var changeFocus = function () {
//      console.log(isActive);
//
//  };
//
//    setInterval(changeFocus,1000);

  document.onmousedown=disableclick;
  function disableclick(event)
  {
    if(event.button==2)
    {
      return false;
    }
  }

</script>

app/views/da_courses/show.html.erb
<div class="ui link cards">
    <% @user.da_courses.each do |dacourse| %>
        <div class="card">
          <a class="image" href="xiaocourseshow?dacourseid=<%= dacourse.id %>">
            <img src=<%= dacourse.imageurl %>>
          </a>
          <div class="content">
            <div class="header"><%= dacourse.content %></div>
            <div class="meta">

            </div>
            <div class="description">

            </div>
          </div>
          <div class="extra content">

          </div>
        </div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>欢迎来到唯新学院网络课堂!</p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于",   "#" %></li>
      <li><%= link_to "联系", '#' %></li>
      <li><a href="#">公告</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%
  if logged_in? && session[:course_time] && !request.original_url.include?('watch')
    @user = User.find_by(id: session[:user_id])
    t1 = Time.parse(session[:course_time])
    t2 = Time.now
    @user.playtime = @user.playtime + (t2 - t1).round(0)
    @user.save
    session.delete(:course_time)
  end

%>


<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "唯新学院", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "课程", dacourseshow_url %></li>
                <li><%= link_to "帐号", edit_user_path(current_user) %></li>
                <% if current_user.admin == true  %>
                    <li><%= link_to "管理", rails_admin_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "退出", logout_path, method: "delete" %></li>
              </ul>
            </li>
        <% else %>
              <li><%= link_to "注册",  signup_path %></li>
              <li><%= link_to "登录", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body oncontextmenu="return false">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for(:session, url: login_path) do |f| %>
              <%= f.label :邮箱 %>
              <%= f.text_field :email %>
              <%= f.label :密码 %>
              <%= f.password_field :password %>
              <%= f.submit "登录", class: "btn btn-primary" %>
          <% end %>
          <p>还没注册? <%= link_to "现在注册吧!", signup_path %></p>
        </div>
      </div>
</div>

app/views/static_pages/login.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "帐号") %>
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <div class="progress">
      <% t = @user.buytime*3600 - @user.playtime %>
      <% tpercent = t.to_f / (@user.buytime*3600) * 100
         mm, ss = t.divmod(60)
         hh, mm = mm.divmod(60) %>
      <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="<%= tpercent %>"
           aria-valuemin="0" aria-valuemax="100" style="width: <%= tpercent %>%;min-width: 4em;">
        <% if hh > 0 && tpercent > 10 %>
            <% tmstring = "剩#{hh}小时#{mm}分" %>
        <% else %>
            <% tmstring = "剩#{mm}分" %>
        <% end %>
        <%=	tmstring %>
      </div>
    </div>
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :姓名 %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :邮箱 %>
        <%= f.text_field :email, class: 'form-control' %>
        <%= f.label :新密码 %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :确认新密码 %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "更新", class: "ui green basic button" %> <% end %>
        </br>
        <%= link_to "取消", current_user, class: "ui grey basic button", style:"width: 100%;" %>
  </div>

</div>

app/views/users/new.html.erb
<% provide(:title, '注册') %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>
          <%= f.label :姓名 %>
          <%= f.text_field :name, class: 'form-control' %>
          <%= f.label :邮箱 %>
          <%= f.text_field :email, class: 'form-control' %>
          <%= f.label :密码 %>
          <%= f.password_field :password, class: 'form-control' %>
          <%= f.label :确认密码 %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
          <%= f.submit "注册", class: "ui green basic button" %>
        <% end %>
      </div>
    </div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui link cards">
  <% if @user.courses.any? %>
      <% @user.courses.each do |course| %>
          <div class="card">
            <a class="image" href="/courseshow?course_now=<%= course.id %>">
              <img src=<%= course.imageurl %>>
            </a>
            <div class="content">
              <div class="header"><%= course.content %></div>
              <div class="meta">
                <p><%= course.teacher %></p>
              </div>
              <div class="description"><%= course.courseinfo %></div>
            </div>
            <div class="extra content">
              <span class="right floated"> <%= course.date %> </span>
              <span><i class="user icon"></i>  <%= course.other %> </span>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

app/views/xiao_courses/show.html.erb
<div class="ui link cards">
  <% @user.xiao_courses.each do |xiaocourse| %>
      <%	if xiaocourse.da_course.id == @current_dacourse.id%>
          <div class="card">
            <a class="image" href="courseshow?xiaocourseid=<%= xiaocourse.id %>">
              <img src=<%= xiaocourse.imageurl %>>
            </a>
            <div class="content">
              <div class="header"><%= xiaocourse.content %></div>
              <div class="meta">

              </div>
              <div class="description">

              </div>
            </div>
            <div class="extra content">

            </div>
          </div>
      <% end %>

  <% end %>
</div>